server:
  port: 8080

spring:
  datasource:
    password: admin
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/product_service_db
    username: postgres

  jpa:
    hibernate:
      ddl-auto: update


